spring.application.name=internhub_be
spring.datasource.url=jdbc:mysql://localhost:3306/internhub?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Tuananh2k5@
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8090
debug=false

# JWT Configuration
app.jwt-secret=yourSuperSecretKeyThatIsAtLeast256BitsLongAndShouldBeStoredSecurely
app.jwt-expiration-milliseconds=604800000

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nguyntanh2k5@gmail.com
spring.mail.password=kfbu qqrc lugy ofqb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com