spring.application.name=internhub_be
spring.datasource.url=jdbc:mysql://localhost:3306/internhub?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Tuananh2k5@
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8090
debug=false

# JWT Configuration
app.jwt-secret=yourSuperSecretKeyThatIsAtLeast256BitsLongAndShouldBeStoredSecurely
app.jwt-expiration-milliseconds=604800000